var events = [{
name: "Billy Ebeling",
description: "",
city: "Kansas City",
country: "United States",
latlng: [39.2428725,-94.6588208],
},
{
name: "our nations Summer capita; is about to pump up the volume",
description: "two nights of dancing to the sounds of two of the Nations TOP Dj&#39;s.. and one T-dance to the sound of our local dj.. There will also be a special performance by a great entertainer. We will be setting up a very large tent that will b able to handle 500 plus people the tent will become a world unto itself.",
city: "Rehoboth Beach",
country: "United States",
latlng: [38.7208,-75.0764],
},
{
name: "ArabAndalus",
description: "",
city: "Valencia",
country: "Spain",
latlng: [42.4,-7.06667],
},
{
name: "*Wakarusa Foundation*",
description: "",
city: "Ozark",
country: "United States",
latlng: [35.7117761,-93.7971925],
},
{
name: "Charli XCX",
description: "",
city: "Las Vegas",
country: "United States",
latlng: [36.1088677,-115.1537786],
},
{
name: "Fat Trel Dmv Life Mixtape Release Show",
description: "",
city: "Washington",
country: "United States",
latlng: [38.915271,-77.021098],
},
{
name: "Live Music @ Murphy's Irish Pub",
description: "  Live Music @ Murphy&#39;s Irish Pub  - Murphy&#39;s Irish Pub - Thu Nov 21 at  7:00PM <p>About Murphy&#39;s Irish Pub</p>  <p>Murphy&rsquo;s Irish Pub in Sonoma offers an authentic traditional pub experience. The founders, Larry and Rose Murphy have recreated the feeling, hospitality and ambiance of a &ldquo;local&rdquo; from a village in Ireland. That tradition is carried on by proprietors Bill Pollock and Bob Smith, long time patrons and researchers of the art of the &ldquo;Pub&rdquo;. Drop in and enjoy a pint, grab a bite to eat, lots of conversation, live music, literary events, weekly trivia events and much more. Not the least of which is that every weekday, between 4:00 & 6:00 you are invited to join us for HAPPY HOUR with discounted pints & appetizers.</p>  <p>Murphy&rsquo;s offers an exceptional variety of beers, both Premium International Beers such as Guinness & Murphy&#39;s Stouts, Smithwicks, Fullers ESB and more, as well as great local and craft beers. &nbsp;An of course we offer a variety of fine Sonoma Valley wines (it is the wine country after all!)</p>  <p>Families are welcome at Murphy&#39;s; kids like our food and parents enjoy the reasonable prices. It&#39;s a friendly atmosphere and we have outdoor seating; the patio is covered and heated in the winter.</p>  <p>Come join us as we listen to great live music (Thursday through Sunday), win a bottles of wine at the Trivia contest (Weds at 7:30). &nbsp;If you&#39;re in Sonoma in the summer time, check out our Tuesday &quot;After Party&quot; - following the Tuesday Night Farmers Market, we BBQ Oysters and have live music outside -7pm-9:30pm. &nbsp;We look forward to see you soon!</p>  <p>- See more at: http://sonomapub.com/about.html#sthash.p2LYoyaj.dpuf</p>  Murphy&#39;s Irish Pub Sonoma CA  - http://sonomapub.com/ <br><br><b>source categories: </b>Music,Food <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>sonomapub ",
city: "Sonoma",
country: "United States",
latlng: [38.2924721,-122.4565503],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Friday Night Live",
description: "Music.",
city: "Hartland",
country: "United States",
latlng: [43.0828,-88.3623],
},
{
name: "Hockey Heroes Meet & Greet at River Rock Casino Resort",
description: " Hockey Heroes Meet & Greet September 07, 2015 at River Rock Casino Resort in Richmond, BC 10:00AM",
city: "Richmond",
country: "Canada",
latlng: [49.1962827,-123.1267608],
},
{
name: "606 Electronic Dance Lounge Thursday EDM Weekly",
description: "NO COVER ONCE YOU RVSP ONCE -- RSVP HERE!:",
city: "Raleigh",
country: "United States",
latlng: [35.7876892,-78.6470956],
},
{
name: "Filthy 13",
description: "",
city: "Kansas City",
country: "United States",
latlng: [39.2428725,-94.6588208],
},
{
name: "Los Angeles DJ",
description: "",
city: "Aliso Viejo",
country: "United States",
latlng: [33.5588163,-117.7231862],
},
{
name: "Saturday Music Live",
description: "Music",
city: "Hartland",
country: "United States",
latlng: [43.0828,-88.3623],
},
{
name: "FBSCC Music Series",
description: " <p>FBSCC Music Series - Artists TBA</p>",
city: "Barrington",
country: "United States",
latlng: [41.740494,-71.307152],
},
{
name: "Live Music @ Murphy's Irish Pub",
description: "  Live Music @ Murphy&#39;s Irish Pub  - Murphy&#39;s Irish Pub - Thu Nov 21 at  7:00PM <p>About Murphy&#39;s Irish Pub</p>  <p>Murphy&rsquo;s Irish Pub in Sonoma offers an authentic traditional pub experience. The founders, Larry and Rose Murphy have recreated the feeling, hospitality and ambiance of a &ldquo;local&rdquo; from a village in Ireland. That tradition is carried on by proprietors Bill Pollock and Bob Smith, long time patrons and researchers of the art of the &ldquo;Pub&rdquo;. Drop in and enjoy a pint, grab a bite to eat, lots of conversation, live music, literary events, weekly trivia events and much more. Not the least of which is that every weekday, between 4:00 & 6:00 you are invited to join us for HAPPY HOUR with discounted pints & appetizers.</p>  <p>Murphy&rsquo;s offers an exceptional variety of beers, both Premium International Beers such as Guinness & Murphy&#39;s Stouts, Smithwicks, Fullers ESB and more, as well as great local and craft beers. &nbsp;An of course we offer a variety of fine Sonoma Valley wines (it is the wine country after all!)</p>  <p>Families are welcome at Murphy&#39;s; kids like our food and parents enjoy the reasonable prices. It&#39;s a friendly atmosphere and we have outdoor seating; the patio is covered and heated in the winter.</p>  <p>Come join us as we listen to great live music (Thursday through Sunday), win a bottles of wine at the Trivia contest (Weds at 7:30). &nbsp;If you&#39;re in Sonoma in the summer time, check out our Tuesday &quot;After Party&quot; - following the Tuesday Night Farmers Market, we BBQ Oysters and have live music outside -7pm-9:30pm. &nbsp;We look forward to see you soon!</p>  <p>- See more at: http://sonomapub.com/about.html#sthash.p2LYoyaj.dpuf</p>  Murphy&#39;s Irish Pub Sonoma CA  - http://sonomapub.com/ <br><br><b>source categories: </b>Music,Food <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>sonomapub ",
city: "Sonoma",
country: "United States",
latlng: [38.2924721,-122.4565503],
},
{
name: "Dominion",
description: "is Ireland&#39;s longest running and only weekly goth, industrial, ebm, & alternative club, now running every Saturday for over 12 years. €3 before 11pm",
city: "Dublin",
country: "Ireland",
latlng: [53.3524533,-6.2610709],
},
{
name: "Récital Masae Barbotte, piano",
description: " <p> à venir </p>",
city: "Paris",
country: "France",
latlng: [48.8522908,2.3573565],
},
{
name: "Tuesday Perryoke Nights",
description: "Best karaoke show there is! $2 Premiums & Down. No Cover Before 10pm. Free Pool 7pm-10pm.",
city: "Stephenville",
country: "United States",
latlng: [32.2144215,-98.214666],
},
{
name: "Jony James",
description: "The Jony James Band is a modern day blues band raised on “old school.” Hard hitting and aimed for your heart, they give you all they’ve got every show.",
city: "Buffalo",
country: "United States",
latlng: [42.813704,-78.824423],
},
{
name: "Live Music @ Murphy's Irish pub",
description: "  Live Music @ Murphy&#39;s Irish pub  - Murphy&#39;s Irish Pub - Sun Nov 10 at  6:30PM <p>About Murphy&#39;s Irish Pub</p>  <p>Murphy&rsquo;s Irish Pub in Sonoma offers an authentic traditional pub experience. The founders, Larry and Rose Murphy have recreated the feeling, hospitality and ambiance of a &ldquo;local&rdquo; from a village in Ireland. That tradition is carried on by proprietors Bill Pollock and Bob Smith, long time patrons and researchers of the art of the &ldquo;Pub&rdquo;. Drop in and enjoy a pint, grab a bite to eat, lots of conversation, live music, literary events, weekly trivia events and much more. Not the least of which is that every weekday, between 4:00 & 6:00 you are invited to join us for HAPPY HOUR with discounted pints & appetizers.</p>  <p>Murphy&rsquo;s offers an exceptional variety of beers, both Premium International Beers such as Guinness & Murphy&#39;s Stouts, Smithwicks, Fullers ESB and more, as well as great local and craft beers. &nbsp;An of course we offer a variety of fine Sonoma Valley wines (it is the wine country after all!)</p>  <p>Families are welcome at Murphy&#39;s; kids like our food and parents enjoy the reasonable prices. It&#39;s a friendly atmosphere and we have outdoor seating; the patio is covered and heated in the winter.</p>  <p>Come join us as we listen to great live music (Thursday through Sunday), win a bottles of wine at the Trivia contest (Weds at 7:30). &nbsp;If you&#39;re in Sonoma in the summer time, check out our Tuesday &quot;After Party&quot; - following the Tuesday Night Farmers Market, we BBQ Oysters and have live music outside -7pm-9:30pm. &nbsp;We look forward to see you soon!</p>  <p>&nbsp;</p>  Murphy&#39;s Irish Pub Sonoma CA  - http://sonomapub.com <br><br><b>source categories: </b>Music,Food <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>sonomapub ",
city: "Sonoma",
country: "United States",
latlng: [38.2924721,-122.4565503],
},
{
name: "The Garrett Nordstrom Experience",
description: "",
city: "Kansas City",
country: "United States",
latlng: [39.2428725,-94.6588208],
},
{
name: "STEVEN KENT -  Dream & Believe",
description: "Singer/Songwriter Steven Kent album debut Dream & Believe - Music from the Heart. Drearm & Believe honors  the great legends of music with vocal accompaniment by the Imperials.",
city: "New York",
country: "United States",
latlng: [40.7502718,-73.9967145],
},
{
name: "Jean Chaine and The Fiction Giants every Thursday",
description: "No Cover",
city: "Wilmington",
country: "United States",
latlng: [42.867935,-72.87252],
},
{
name: "Bluegrass with Dave Talmage",
description: "Bluegrass Jam with Dave Talmage",
city: "Newmarket",
country: "United States",
latlng: [43.078904,-70.938184],
},
{
name: "OPUS festival Sedmihorske leto 2013",
description: "AUSTRIA LEGEND IN FIRST CONCERT IN CZECH REPUBLIC!!!!! WWW.SEDMIHORSKELETO.CZ",
city: "Turnov",
country: "Czech Republic",
latlng: [50.5858,15.1483],
},
{
name: "ROCKIN CLUB MADRID",
description: "",
city: "Madrid",
country: "Spain",
latlng: [40.4,-3.68333],
},
{
name: "George Lucas Sings the Blues",
description: "This might be happening.",
city: "Chicago",
country: "United States",
latlng: [41.9693065,-87.6762185],
},
{
name: "Acoustic Showcase",
description: "Singers, songwriters, and other acoustic acts starting at 8pm every Wednesday. Homemade liquor infusions, exotic cocktails, craft beer on tap, and two pool tables as well.",
city: "North Hollywood",
country: "United States",
latlng: [34.172444,-118.359151],
},
{
name: "Open Mic @ Corkscrew PDX",
description: "  Open Mic @ Corkscrew PDX   - http://corkscrewpdx.com/ - Mon Jun  3 at  7:00PM <p>&nbsp;</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Open Mic @ Corkscrew PDX",
description: "  Open Mic @ Corkscrew PDX   - http://corkscrewpdx.com/ - Mon Jun  3 at  7:00PM <p>&nbsp;</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Vanguard Jazz Ensamble Murphy's Irish Pub",
description: "  Vanguard Jazz Ensamble Murphy&#39;s Irish Pub   - Murphy&#39;s Irish Pub - Sun Nov 10 at  2:00PM <p>A weekly jazz jam session open to all players and jazz lovers.</p>  Murphy&#39;s Irish Pub Sonoma CA  - http://sonomapub.com <br><br><b>source categories: </b>Music,Food <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>sonomapub ",
city: "Sonoma",
country: "United States",
latlng: [38.2924721,-122.4565503],
},
{
name: "Open Mic @ Corkscrew PDX",
description: "  Open Mic @ Corkscrew PDX   - http://corkscrewpdx.com/ - Mon Jun  3 at  7:00PM <p>&nbsp;</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "DJ Trivia in Raleigh at Wild Wing Cafe",
description: "Free to play / food and drink are available for purchase on site.",
city: "Raleigh",
country: "United States",
latlng: [35.9142129,-78.781148],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "TWISTED NAIL LIFETIME VIP",
description: " The TWISTED NAIL LIFETIME VIP package is unbeatable! For $550, you will have a lifetime pass to all TNP produced shows (they have to have the TNP banner to be conisdered, ie no random tour dates). This will include the VIP perks for all shows you want to attend, as well as a customized VIP laminate! <br> <br>To attend shows, all we ask is that you notify us two weeks before a show! <br> <br>P.S. While it says the HOUSE OF ROCK above, not all TNP shows are booked there! So be sure to follow our site & social medis for updates! <br> <br>*THIS EXCLUDES CHARITY SHOWS.",
city: "White Marsh",
country: "United States",
latlng: [39.39726,-76.404752],
},
{
name: "Worship Service",
description: "Stewartstown Baptist Church located in Stewartstown, Pennsylvania. We are a group of people who are Seeking the Lord through worship, Building relationships with others, and Committed to serve the world for Christ. Come be a part of what God is doing here at SBC.",
city: "Stewartstown",
country: "United States",
latlng: [39.7577349,-76.616313],
},
{
name: "Coffee Talk with Chelle",
description: "",
city: "Fort Worth",
country: "United States",
latlng: [32.8673,-97.2486],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Live Music @ Corkscrew PDX",
description: "  Live Music @ Corkscrew PDX   - http://corkscrewpdx.com/ - Thu Jun 13 at  8:00PM  Corkscrew Wine Bar Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Salsa Night",
description: " The Mexican Café was established in 1983 and has since become an institution in Auckland and beyond. The restaurant offers food, drinks, ...",
city: "Auckland",
country: "New Zealand",
latlng: [-36.8667,174.767],
},
{
name: "Youth Dance - Jazz & Hip Hop, 7 - 14 yrs.",
description: " ",
city: "De Pere",
country: "United States",
latlng: [44.444878,-88.078362],
},
{
name: "Title Boxing Club Presents Friday Night Fights",
description: "",
city: "Columbus",
country: "United States",
latlng: [39.969862,-83.010397],
},
{
name: "Live Music @ Murphy's Irish pub",
description: "  Live Music @ Murphy&#39;s Irish pub  - Murphy&#39;s Irish Pub - Sun Nov 10 at  6:30PM <p>About Murphy&#39;s Irish Pub</p>  <p>Murphy&rsquo;s Irish Pub in Sonoma offers an authentic traditional pub experience. The founders, Larry and Rose Murphy have recreated the feeling, hospitality and ambiance of a &ldquo;local&rdquo; from a village in Ireland. That tradition is carried on by proprietors Bill Pollock and Bob Smith, long time patrons and researchers of the art of the &ldquo;Pub&rdquo;. Drop in and enjoy a pint, grab a bite to eat, lots of conversation, live music, literary events, weekly trivia events and much more. Not the least of which is that every weekday, between 4:00 & 6:00 you are invited to join us for HAPPY HOUR with discounted pints & appetizers.</p>  <p>Murphy&rsquo;s offers an exceptional variety of beers, both Premium International Beers such as Guinness & Murphy&#39;s Stouts, Smithwicks, Fullers ESB and more, as well as great local and craft beers. &nbsp;An of course we offer a variety of fine Sonoma Valley wines (it is the wine country after all!)</p>  <p>Families are welcome at Murphy&#39;s; kids like our food and parents enjoy the reasonable prices. It&#39;s a friendly atmosphere and we have outdoor seating; the patio is covered and heated in the winter.</p>  <p>Come join us as we listen to great live music (Thursday through Sunday), win a bottles of wine at the Trivia contest (Weds at 7:30). &nbsp;If you&#39;re in Sonoma in the summer time, check out our Tuesday &quot;After Party&quot; - following the Tuesday Night Farmers Market, we BBQ Oysters and have live music outside -7pm-9:30pm. &nbsp;We look forward to see you soon!</p>  <p>&nbsp;</p>  Murphy&#39;s Irish Pub Sonoma CA  - http://sonomapub.com <br><br><b>source categories: </b>Music,Food <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>sonomapub ",
city: "Sonoma",
country: "United States",
latlng: [38.2924721,-122.4565503],
},
{
name: "Rick Baccus Trio",
description: "",
city: "Kansas City",
country: "United States",
latlng: [39.2428725,-94.6588208],
},
{
name: "Live Music with Bobby and Frankie May",
description: "Live music with Bobby May ,Frank May and Friends!!Can&#39;t Wait!Gonna B A Party:)Don&#39;t forget &quot;Good Ole Gary&#39;s&quot; New York Strip steak dinners!!!Yummy!!!",
city: "Toledo",
country: "United States",
latlng: [41.628257,-83.513008],
},
{
name: "Spring Dance 2013",
description: "The Progressive Men&#39;s Club of Hagerstown and Off The Block are proud to present its Spring Dance 2013 on May 18,2013 from 9pm to 1am at the VFW 70 E. Washington St.Tickets are $10 in advance and $12 at at the  door. Advance tickets can be purchased from members of both organizations. Admissions includes free draft beer. feel free to bring your favorite food! Call Kirky at 3016659165 or Merrill 3019911113.",
city: "Hagerstown",
country: "United States",
latlng: [39.639493,-77.714939],
},
{
name: "STEVEN KENT -  Dream & Believe",
description: "Singer/Songwriter Steven Kent Debut-Album Dream & Believe - Musik aus dem Herzen. Drearm & glauben zu Ehren des großen Legenden der Musik mit vokale Begleitung von den Imperials.",
city: "Hamburg",
country: "Germany",
latlng: [53.5491576,9.9633747],
},
{
name: "LBRAPPER lil walks my life",
description: "lbrapper is from canada me and my bro lil walks are from barrie where awesome rappers i hope u like the show",
city: "Barrie",
country: "Canada",
latlng: [44.4120476,-79.6677522],
},
{
name: "Karaoke Monday nights Fowlers Grange Cross, Ballyfermot",
description: "Fowlers Karaoke night, Every monday night, come along for a great night, good buzz and fab singers!",
city: "Dublin",
country: "Ireland",
latlng: [53.3416,-6.25735],
},
{
name: "Dancing with Donna to the band JUST BREAKING EVEN,,,,,,",
description: "Just Breaking Even ....a band is here..,.....2 Step, Electric slide, Cowboy Cha Cha , Cowboy Hustle, Cowboy Charleston, Choc. City Hustle, 5 Step, Cupid Shuffle, and many more . We dance from 7:00 to 9:30 come Join us,..,,,,",
city: "Murray",
country: "United States",
latlng: [36.6234891,-88.3017675],
},
{
name: "Sunday Worship Serivce",
description: "Stewartstown Baptist Church located in Stewartstown, Pennsylvania. We are a group of people who are Seeking the Lord through worship, Building relationships with others, and Committed to serve the world for Christ. Come be a part of what God is doing here at SBC.",
city: "Stewartstown",
country: "United States",
latlng: [39.7577349,-76.616313],
},
{
name: "Maria Gadu",
description: "",
city: "Miami Beach",
country: "United States",
latlng: [25.792917,-80.13314],
},
{
name: "BedHead presents Icona Pop at Commodore Ballroom",
description: " BedHead presents Icona Pop September 27, 2015 at Commodore Ballroom in Vancouver, BC 8:00PM",
city: "Vancouver",
country: "Canada",
latlng: [49.2806502,-123.1208713],
},
{
name: "Upcoming Library Events",
description: "Events for adults & kids of all ages. ",
city: "Saint Charles",
country: "United States",
latlng: [41.9138026,-88.3075811],
},
{
name: "STEVEN KENT -  Dream & Believe",
description: "Singer/Songwriter Steven Kent album debut Dream & Believe - Music from the Heart. Honoring the great legends of music with vocal accompaniment by the Imperials. On Demand - Buy Today!",
city: "San Francisco",
country: "United States",
latlng: [37.7982029,-122.4274255],
},
{
name: "S.O.L Entertainment",
description: "",
city: "New York",
country: "United States",
latlng: [40.7142,-74.0064],
},
{
name: "Guangzhou Car Hire Shenzhen Foshan Taxi Transfer with Driver",
description: "With more than 8 years Great China tour experiences, Canton Car Rental provides professional Guangzhou & Shenzhen airport & location transfer by different cars, sedans, vans, coaches, air-conditioned deluxe tour bus! ",
city: "",
country: "China",
latlng: [23.0978401,113.3797039],
},
{
name: "Music Thursday",
description: "  Music Thursday  - Corkscrew PDX - Thu Jan  2 at  8:00PM   Portland OR  <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
},
{
name: "JAYLARNO's POPULAR 70s & 80s ROOTS REGGAE NIGHT – EVERY WEDNESDAY",
description: "JAYLARNO&#39;s POPULAR 70s & 80s ROOTS REGGAE NIGHT – EVERY WEDNESDAY",
city: "Dollis Hill",
country: "United Kingdom",
latlng: [51.5570502,-0.215612],
},
{
name: "''THE KUSH-GIVE-A-WAY'' // LIVE WITH ''G.A. THA GENERAL''",
description: "OUTSIDE EVENT START@ 6P.M. ENDS@9P.M.  // $5.00 ENTRY//  ALSO ENTER -IN  &#39;&#39;THE KUSH-GIVE-WAY&#39;&#39; TO WIN A MONTH OR A YEAR SUPPLY OF THE ALL NEW &#39;&#39;KUSH SERIES BLUNT WRAPS&#39;&#39;... SPONSORS BY &#39;&#39;ROYAL BLUNTS&#39;&#39; // BALLERS CHOICE//XXL WRAPS// MIZUNDASTOOD CLOTHING WEAR// .  PERFORMANCE BY   G.A. THA GENERAL FROM WUNDER BOY RECORDS DOING TRACKS OFF HIS ALL NEW ALBUM &#39;&#39;K.U.S.H. DAZE B.C. 2012&#39;&#39;  COMING SOON FOR ONLY $0.99 CENTS . SPECIAL GUEST   Amaretto The Young God ,OTHERS ARTIST  T.B.A.&#39;&#39; THE SMOKE WILL NEVER CLEAR &#39;&#39;",
city: "Saint Petersburg",
country: "United States",
latlng: [27.8420994,-82.6386236],
},
{
name: "Henry + The Invisibles Live @ Rebar",
description: "",
city: "San Antonio",
country: "United States",
latlng: [29.511042,-98.465915],
},
{
name: "Live DJ Spinning Tunes at Rockhouse Bar & Grill + Crazy Drink Specials",
description: "DJ EmC will be mixing it up behind the 1s-n-2s and taking all your requests! $3 Shots. $2.50 Margaritas. $5 Long Islands.",
city: "Houston",
country: "United States",
latlng: [29.7979411,-95.6450068],
},
{
name: "The Oberon Community Middle Eastern Music & Dance Show",
description: "The Blue Monk presents ARABESQUE every Wednesday at 8 PM.  The band performs traditional Middle Eastern (Turkish, Arabic, Persian and Armenian) Music and features all of the hundreds of local/regional Middle Eastern Tribal and Belly Dancers. ",
city: "Portland",
country: "United States",
latlng: [45.5165612,-122.6299355],
},
{
name: "Live Music at Farmstead at Long Meadow Ranch",
description: "  Live Music at Farmstead at Long Meadow Ranch  - Long Meadow Ranch - Fri Dec 20 at  5:00PM <p>Friday&nbsp;: Live Music</p>  <p>Enjoy the rowdy classic country music of the Jimi James Band at the Outdoor Bar every&nbsp;Friday&nbsp;starting at&nbsp;5pm.</p>  Farmstead at Long Meadow Ranch St. Helena CA  - http://www.longmeadowranch.com/Farmstead-Restaurant <br><br><b>source categories: </b>Wine,Community <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>longmeadow ",
city: "Saint Helena",
country: "United States",
latlng: [38.501023,-122.463144],
},
{
name: "Live Music @ Murphy's Irish pub",
description: "  Live Music @ Murphy&#39;s Irish pub  - Murphy&#39;s Irish Pub - Sun Nov 10 at  6:30PM <p>About Murphy&#39;s Irish Pub</p>  <p>Murphy&rsquo;s Irish Pub in Sonoma offers an authentic traditional pub experience. The founders, Larry and Rose Murphy have recreated the feeling, hospitality and ambiance of a &ldquo;local&rdquo; from a village in Ireland. That tradition is carried on by proprietors Bill Pollock and Bob Smith, long time patrons and researchers of the art of the &ldquo;Pub&rdquo;. Drop in and enjoy a pint, grab a bite to eat, lots of conversation, live music, literary events, weekly trivia events and much more. Not the least of which is that every weekday, between 4:00 & 6:00 you are invited to join us for HAPPY HOUR with discounted pints & appetizers.</p>  <p>Murphy&rsquo;s offers an exceptional variety of beers, both Premium International Beers such as Guinness & Murphy&#39;s Stouts, Smithwicks, Fullers ESB and more, as well as great local and craft beers. &nbsp;An of course we offer a variety of fine Sonoma Valley wines (it is the wine country after all!)</p>  <p>Families are welcome at Murphy&#39;s; kids like our food and parents enjoy the reasonable prices. It&#39;s a friendly atmosphere and we have outdoor seating; the patio is covered and heated in the winter.</p>  <p>Come join us as we listen to great live music (Thursday through Sunday), win a bottles of wine at the Trivia contest (Weds at 7:30). &nbsp;If you&#39;re in Sonoma in the summer time, check out our Tuesday &quot;After Party&quot; - following the Tuesday Night Farmers Market, we BBQ Oysters and have live music outside -7pm-9:30pm. &nbsp;We look forward to see you soon!</p>  <p>&nbsp;</p>  Murphy&#39;s Irish Pub Sonoma CA  - http://sonomapub.com <br><br><b>source categories: </b>Music,Food <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>sonomapub ",
city: "Sonoma",
country: "United States",
latlng: [38.2924721,-122.4565503],
},
{
name: "THE DALLAS DAYTIME EXPERIENCE with KARAOKE & OPEN MIC",
description: "EMOEVENTS | LIKE MINDS UNLIMITED | DFW PARTY PUSHER",
city: "Dallas",
country: "United States",
latlng: [32.7809884,-96.7934229],
},
{
name: "Helene Fischer Die Stadion Tournee 2015",
description: "",
city: "Cologne",
country: "Germany",
latlng: [50.93753,6.87462],
},
{
name: "Freebirds Unplugged Brunch",
description: "Similar to the vibe during MTV&#39;s Unplugged series, live acoustic music performances from various local and national artists, will be performed at FREEBIRDS Shepherd Plaza Unplugged Weekend Brunch.",
city: "Houston",
country: "United States",
latlng: [29.7328212,-95.4127701],
},
{
name: "STEVEN KENT -  Dream & Believe",
description: "Would He Believe onderscheidingen Elvis Presley en zijn nalatenschap, geschreven en gezongen door Steven Kent, vocale begeleiding de Imperials Imperials-Elvis",
city: "Amsterdam",
country: "Netherlands",
latlng: [52.3612332,4.9163277],
},
{
name: "free stand up COMEDY COMEDY. show every Sunday 7:30 pm TO midnight",
description: "Free STAND up comedy SHOW TONITE and every  SUNDAY 7:30 PM to midnight.",
city: "Tempe",
country: "United States",
latlng: [33.41462466355754,-111.91100073743439],
},
{
name: "Alka Yagnik & Udit Narayan",
description: "",
city: "Lynn",
country: "United States",
latlng: [42.464808,-70.9512139],
},
{
name: "Worship Service",
description: "Stewartstown Baptist Church located in Stewartstown, Pennsylvania. We are a group of people who are Seeking the Lord through worship, Building relationships with others, and Committed to serve the world for Christ. Come be a part of what God is doing here at SBC.",
city: "Stewartstown",
country: "United States",
latlng: [39.7577349,-76.616313],
},
{
name: "Ruben Joshua Moreno",
description: "Ruben Joshua Moreno",
city: "Dallas",
country: "United States",
latlng: [32.7873643,-96.7965647],
},
{
name: "ThursDaze College Nights at Sharkeez",
description: "ThursDaze COLLEGE NIGHT at Baja Sharkeez Newport Beach!",
city: "Newport Beach",
country: "United States",
latlng: [33.608949,-117.9277152],
},
{
name: "STEVEN KENT -  Dream & Believe",
description: "",
city: "Rio de Janeiro",
country: "Brazil",
latlng: [-22.9,-43.2333],
},
{
name: "International Harp Contest in Israel",
description: " <p>Divided into four stages and requiring competitors to play both from memory and from scores, the International Harp Contest is a serious and enriching experience. ...</p>",
city: "Jerusalem",
country: "Israel",
latlng: [31.78,35.22],
},
{
name: "Quarter Beer Night",
description: "$7 Bracelets gets you Quarter Beer 9pm-midnight.",
city: "Tulsa",
country: "United States",
latlng: [36.1548248,-95.986201],
},
{
name: "Latino Nights at Blondies Ultra Lounge",
description: "Free Salsa & Bachata Lessons, every Thursday at 8:30pm.",
city: "Colorado Springs",
country: "United States",
latlng: [38.834933,-104.823916],
},
{
name: "Karaoke Thursday nights Swallows Clondalkin",
description: "Swallows Karaoke night, Every Thursday night, come along for a great night, good buzz and fab singers!",
city: "Dublin",
country: "Ireland",
latlng: [53.3416,-6.25735],
},
{
name: "SHOWTECH",
description: " SHOWTECH ",
city: "Doha",
country: "United States",
latlng: [25.2867,51.5333],
},
{
name: "WHAT IT DO TUESDAYS | OPEN MIC SHOWCASE",
description: "COME ROCK THE STAGE W/ BAYLIFE ENT!",
city: "San Leandro",
country: "United States",
latlng: [37.7319825,-122.1611561],
},
{
name: "Open Stage",
description: "Got Talent?  Join our host, Dale Kulchar, on stage at the Grill!  Everyone welcome, solo and duos to full blown bands.",
city: "Pomeroy",
country: "United States",
latlng: [39.0271151,-82.033404],
},
{
name: "U Wanna Dance *Swing*Blues*Cajun*Zydeco*",
description: "http://www.uwannadance.com is a FREE service for Dancers interested in being connected to the Swing, Blues, Cajun & Zydeco Dance Community in the Twin Cities.  The Monthly Calendar and Links to Venues, Bands, Instruction and other Dance Groups is an excellent resource for dancers looking for opportunities to Dance and hone, or develop, their skills.....Check it out TODAY!!!....http://uwannadance.com/Home_Page.php....Hope to see you on the Dance Floor Soon!",
city: "Minneapolis",
country: "United States",
latlng: [44.98,-93.2636],
},
{
name: "Vince Neil",
description: "",
city: "Beaumont",
country: "United States",
latlng: [30.014058612196376,-94.17451517319944],
},
{
name: "Live Music at The Wine Kitchen",
description: "  Live Music at The Wine Kitchen  - The Wine Kitchen - Sun Jul 21 at 12:00PM <p>The Wine Kitchen, Leesburg7 South King StreetLeesburg, VA 20175</p>  <p><strong>***We have live music every Sunday from 12pm to 3pm***</strong></p>  The Wine Kitchen Leesburg VA  - http://www.thewinekitchen.com/ <br><br><b>source categories: </b>Food <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>savor ",
city: "Leesburg",
country: "United States",
latlng: [39.1153068,-77.5650196],
},
{
name: "Kanikapila Nights Come Plug-in and Play",
description: "Kanikapila 7p - 10p | FREE",
city: "Kahuku",
country: "United States",
latlng: [21.697724,-157.9927856],
},
{
name: "Movimento Teen",
description: "",
city: "Nilópolis",
country: "Brazil",
latlng: [-22.8069,-43.4117],
},
{
name: "All Arts Open Mic",
description: "The All Arts Open Mic takes place every Wednesday night at the Funky Buddha Lounge in Boca Raton.",
city: "Boca Raton",
country: "United States",
latlng: [26.374622,-80.076854],
},
{
name: "Surprise Club Berlin - Black Music PARTY Saturday",
description: "Ab 22:00 Uhr darf gefeiert, getrunken und getanzt werden.",
city: "Berlin",
country: "Germany",
latlng: [52.50351,13.36564],
},
{
name: "Nexus Events | Momo Lounge Featuring Music By Katz",
description: "Dj Katz wants you to come support and celebrate his 6 year anniversary with the Momo Lounge. Momo lounge continues to be one of the Best nightclubs in Saramento, and we are excited and so thankful for your continuing support over the years.",
city: "Sacramento",
country: "United States",
latlng: [38.573737,-121.470146],
},
{
name: "Staggerwing Country Music Jamboree !",
description: "Staggerwing country jamboree is a great place to bring the whole family for a great night of country music and dancing ! Super dance floor, Great band with Gary page & the country rockers. Come out and listen to Billy Wilson / Robert Price / Lalla Lehmann / Jason Duckwothworth / Emmitt Page / William Brinson / RJ Brinson / and other local drop in talent from surrounding county's. Fre super at 9:00pm every friday night. 50/50 drawings and Super nice prize giveaway at 9:00pm and 11:00pm. located at Spence Field / Sunbelt Expo. Moultrie Georgia.2099 Highway 133 south. Love to see you there. Load up the station wagon and come on out ! No cover charge or fee's to pay.",
city: "Moultrie",
country: "United States",
latlng: [31.1695,-83.7851],
},
{
name: "Vanguard Jazz Ensamble Murphy's Irish Pub",
description: "  Vanguard Jazz Ensamble Murphy&#39;s Irish Pub   - Murphy&#39;s Irish Pub - Sat Nov 16 at  2:00PM <p>A weekly jazz jam session open to all players and jazz lovers.</p>  Murphy&#39;s Irish Pub Sonoma CA  - sonomapub.com <br><br><b>source categories: </b>Music,Food <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>sonomapub ",
city: "Sonoma",
country: "United States",
latlng: [38.2924721,-122.4565503],
},
{
name: "Wine tasting Wednesdays @ Corkscrew PDX",
description: "  Wine tasting Wednesdays @ Corkscrew PDX  - Corkscrew PDX - Wed Jun  5 at  5:30PM <p>Sake&#39; herbal tonics w/ Stephanie from the Healing Arts Resource Project</p>  <p>&nbsp;</p>  Corkscrew PDX Portland OR  - http://corkscrewpdx.com/ <br><br><b>source categories: </b>Wine,Music <br><br><b>event syndication</b> by <b><i>Syndical.com<i></i></i></b> <br><br><b>from Account: </b>corkscrew ",
city: "Portland",
country: "United States",
latlng: [45.473753,-122.6483744],
}
];
